export const CREATE_POST = 'POST/CREATE_POST'
export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'

export const SHOW_LOADER = 'UI/SHOW_LOADER'
export const HIDE_LOADER = 'UI/HIDE_LOADER'

export const SHOW_ALERT = 'UI/SHOW_ALERT'
export const HIDE_ALERT = 'UI/HIDE_ALERT'